#!/bin/bash
# Merge two SRT subtitle files. Only the main subtitle timestamp is preserved while the translated
# subtitle timestamp is replaced with the main subtitle timestamp with matching section number. section_offset
# is to adjust section number between the two. i.e. offset 6 means the first 6 main subtitle has no
# translation so the 7th main subtitle maps to the 1st translate subtitle section; -4 means main subtitle
# misses its first 4 section, so the 1st main subtitle maps to the 5th translated subtitle section.

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")	# to support space in file name
SECT_OFF=$3		# section number offset
CUR_SECT=0		# current processed section number

usage() {
	echo $1 "<main_subtitle> <translated_subtitle> [section_offset]"
	exit
}

# Trim Window carriage return for later empty line parsing
trim() {
	local var="$*"
	var="${var%"${var##*[![:space:]]}"}"
	echo -n "$var"
}

# Dump or skip one section of subtitle. Return false if EOF
dump_one_sub_sect() {
	fd=$1		# file descriptor, 0 for main subtitle, 3 for translated subtile
	skip=$2		# skip 2 lines for translated subtitle since its timestamp is not needed
	font=$3 	# add <i>, <b> etc wrapper to highlight subtitle text

	# skip leading empty lines
	while read -u $fd line; do
		line=$(trim $line)
		[ ! -z "$line" ] && break
	done

	# EOF
	[ -z $line ] && return -1

	# dump section number and timestamp portion
	CUR_SECT=$line
	(( skip-- ))
	[ $skip -ge 0 ] || echo $line
	if read -u $fd line; then
		line=$(trim $line)
		(( skip-- ))
		[ $skip -ge 0 ] || echo $line 
	fi

	# dump subtitle text portion
	while read -u $fd line; do
		line=$(trim $line)
		[ -z "$line" ] && break
		(( skip-- ))
		if [[ $skip -lt 0 ]]; then
			if [ ! -z $font ]; then
				echo "<$font>"$line"</$font>"
			else
				echo $line 
			fi
		fi
	done
	return 0
}

[ $# -lt 2 ] && usage $0
offset=$SECT_OFF
while true; do
	# adjust start sections; dump first n sections of original substile wihtout translated subtile 
	if [[ $offset -gt 0 ]]; then
		dump_one_sub_sect 0 0 || break
		(( offset-- ))
		echo	# leave an empty line
		continue
	fi 

	# adjust start sections; skip first n sections of tranlsated subtitle without main subtitle
	if [[ $offset -lt 0 ]]; then
		>> /dev/null dump_one_sub_sect 3 0
		(( offset++ ))
		continue
	fi

	# dump one section of original subtitle
	dump_one_sub_sect 0 0 || break

	# dump one section of translated subtitle
	sect=$CUR_SECT
	dump_one_sub_sect 3 2 "i" || continue
	(( idx_diff=sect-SECT_OFF-CUR_SECT ))
	if [[ $idx_diff -ne 0 ]]; then
		>&2 echo "Error: $1:$sect mismatch $2:$CUR_SECT"
		break;
	fi

	# Leave an empty line between merged section
	echo
done < $1 3< $2
IFS=$SAVEIFS
